# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
