# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_auto_20161117_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_address',
        ),
    ]
