# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses_app', '0004_auto_20161120_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assigned',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='stuednt',
            field=models.ManyToManyField(related_name='courses', to='authentication.User'),
        ),
        migrations.DeleteModel(
            name='Assigned',
        ),
    ]
